In [3]:
#import io
from google.colab import drive
drive.mount("/content/drive/")

Mounted at /content/drive/


## Load the dataset

In [4]:
import pandas as pd
df=pd.read_excel(r'/content/drive/MyDrive/Merged_BothDS_Dataset-1.xlsx')
df

Problem    Equation Sollution  \
0     সানির কিছু মার্বেল রয়েছে। তিনি ৪৮৯ মার্বেল কি...    ২৭৭৮-৪৮৯      1929   
1     কমলির ১২১ টি খেলনা ছিল। এখন তার ২২ টি খেলনা আছ...      ১২১-২২        99   
2     কমলিনির কিছু মার্বেল ছিল। সে জুয়ানকে ১৮৩ গুলি...     ৫৯৩-১৮৩       410   
3     কনিকার ২৩১৫ টি লাল কলম এবং ১০২৮ টি নীল কলম রয়...   ২৩১৫+১০২৮      3343   
4     ইশিতার ৩৪৪ টি বই রয়েছে। ২৩৬ টি গল্পের বই এবং ...     ৩৪৪-২৩৬       108   
...                                                 ...         ...       ...   
8654  পুরুলিয়ার একটি মেলায় অমল ৯৫ টাকাতে একটি ব্যাগ ...       ৯৫*১৮      1710   
8655  আমাদের গ্রামে ১২৫ টি পরিবার বসবাস করে। পরিবেশ ...      ১২৫*১৭      2125   
8656  বিবেকানন্দ কলোনিতে মোট ১২৮ জন শিশু আছে। প্রত্য...      ১২৫*২৮      3500   
8657  শাহানাকে ১৬ টাকা দামের কয়েকটি জলের বোতল কিনতে ...        ৪৮/৬         8   
8658  পৃথা বাজার থেকে ২৫০গ্রাম পেঁয়াজ, ৫০ গ্রাম রসুন...  ২৫০+৫০+৩০০       600   

     Class  
0        -  
1        -  
2        -  
3        +  
4        -  
...    ...  
8654     *  
8655     *  
8656     *  
8657     /  
8658     +  

[8659 rows x 4 columns]

In [5]:
df = df.dropna()
df

Problem    Equation Sollution  \
0     সানির কিছু মার্বেল রয়েছে। তিনি ৪৮৯ মার্বেল কি...    ২৭৭৮-৪৮৯      1929   
1     কমলির ১২১ টি খেলনা ছিল। এখন তার ২২ টি খেলনা আছ...      ১২১-২২        99   
2     কমলিনির কিছু মার্বেল ছিল। সে জুয়ানকে ১৮৩ গুলি...     ৫৯৩-১৮৩       410   
3     কনিকার ২৩১৫ টি লাল কলম এবং ১০২৮ টি নীল কলম রয়...   ২৩১৫+১০২৮      3343   
4     ইশিতার ৩৪৪ টি বই রয়েছে। ২৩৬ টি গল্পের বই এবং ...     ৩৪৪-২৩৬       108   
...                                                 ...         ...       ...   
8654  পুরুলিয়ার একটি মেলায় অমল ৯৫ টাকাতে একটি ব্যাগ ...       ৯৫*১৮      1710   
8655  আমাদের গ্রামে ১২৫ টি পরিবার বসবাস করে। পরিবেশ ...      ১২৫*১৭      2125   
8656  বিবেকানন্দ কলোনিতে মোট ১২৮ জন শিশু আছে। প্রত্য...      ১২৫*২৮      3500   
8657  শাহানাকে ১৬ টাকা দামের কয়েকটি জলের বোতল কিনতে ...        ৪৮/৬         8   
8658  পৃথা বাজার থেকে ২৫০গ্রাম পেঁয়াজ, ৫০ গ্রাম রসুন...  ২৫০+৫০+৩০০       600   

     Class  
0        -  
1        -  
2        -  
3        +  
4        -  
...    ...  
8654     *  
8655     *  
8656     *  
8657     /  
8658     +  

[8658 rows x 4 columns]

## Data Preprocessing

In [6]:
!pip3 install bnltk

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.2/79.2 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 49.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 72.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 59.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.3/615.3 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 73.9 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.17.1
    Uninstalling tensorboard-2.17.1:
      Successfully uninstalled tensorboard-2.17.1
  Attempting uninstall: scikit-learn
    Foun

In [7]:
df['Problem'][1]

'কমলির ১২১ টি খেলনা ছিল। এখন তার ২২ টি খেলনা আছে, তাহলে সে কতগুলো খেলনা হারিয়ে ফেলেছে?'

In [8]:
# Get tokens and remove punctuation

import string
from bnltk.tokenize import Tokenizers

t = Tokenizers()
problem_lines=[]

for line in df['Problem']:
  tokens = t.bn_word_tokenizer(line)
  problem_lines.append(tokens)
  #break

problem_lines[0:5]


[['সানির',
  'কিছু',
  'মার্বেল',
  'রয়েছে',
  '।',
  'তিনি',
  '৪৮৯',
  'মার্বেল',
  'কিনেছিলেন',
  '।',
  'এখন',
  'তার',
  'সব',
  'মিলিয়ে',
  '২৭৭৮',
  'মার্বেল',
  'রয়েছে',
  '।',
  'তিনি',
  'কয়টি',
  'দিয়ে',
  'শুরু',
  'করেছিলেন',
  '?'],
 ['কমলির',
  '১২১',
  'টি',
  'খেলনা',
  'ছিল',
  '।',
  'এখন',
  'তার',
  '২২',
  'টি',
  'খেলনা',
  'আছে',
  ',',
  'তাহলে',
  'সে',
  'কতগুলো',
  'খেলনা',
  'হারিয়ে',
  'ফেলেছে',
  '?'],
 ['কমলিনির',
  'কিছু',
  'মার্বেল',
  'ছিল',
  '।',
  'সে',
  'জুয়ানকে',
  '১৮৩',
  'গুলি',
  'মার্বেল',
  'দিয়েছে',
  '।',
  'এখন',
  'তার',
  'হাতে',
  'রয়েছে',
  '৫৯৩',
  'টি',
  'মার্বেল',
  '।',
  'প্রথমে',
  'তার',
  'কতগুলি',
  'মার্বেল',
  'ছিল',
  '?'],
 ['কনিকার',
  '২৩১৫',
  'টি',
  'লাল',
  'কলম',
  'এবং',
  '১০২৮',
  'টি',
  'নীল',
  'কলম',
  'রয়েছে',
  '।',
  'তার',
  'মোট',
  'কতটি',
  'কলম',
  'রয়েছে',
  '?'],
 ['ইশিতার',
  '৩৪৪',
  'টি',
  'বই',
  'রয়েছে',
  '।',
  '২৩৬',
  'টি',
  'গল্পের',
  'বই',
  'এবং',
  'বাকিগুলি',
  'খেলা

In [9]:
# Convert Problem sequences to tokenizers
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(problem_lines)

sequence=tokenizer.texts_to_sequences(problem_lines)

sequence[0]

[1283,
 72,
 66,
 5,
 1,
 16,
 1741,
 66,
 126,
 1,
 17,
 12,
 58,
 60,
 1882,
 66,
 5,
 1,
 16,
 20,
 76,
 106,
 96,
 3]

In [10]:
word_index = tokenizer.word_index
print(word_index)

{'।': 1, 'টি': 2, '?': 3, 'কত': 4, 'রয়েছে': 5, 'টাকা': 6, 'আছে': 7, 'মোট': 8, 'কাছে': 9, 'এবং': 10, 'ছিল': 11, 'তার': 12, ',': 13, 'একটি': 14, 'করে': 15, 'তিনি': 16, 'এখন': 17, 'কতগুলি': 18, 'তবে': 19, 'কয়টি': 20, '.': 21, 'জন': 22, 'আরও': 23, 'প্রতিটি': 24, 'মাইল': 25, '১০': 26, '৪': 27, '৫': 28, 'গাছ': 29, 'থেকে': 30, '২': 31, 'যদি': 32, '৩': 33, '২০': 34, 'বই': 35, 'সে': 36, '৬': 37, 'থাকবে': 38, '৮': 39, 'আর': 40, '৫০': 41, 'করেছে': 42, 'আপেল': 43, 'দাম': 44, '৭': 45, 'হবে': 46, 'জন্য': 47, 'বাক্সে': 48, '০': 49, 'বেলুন': 50, 'প্রতি': 51, 'তারা': 52, 'ঘন্টা': 53, 'পেন্সিল': 54, 'করতে': 55, 'কলম': 56, '৩০': 57, 'সব': 58, 'তোমার': 59, 'মিলিয়ে': 60, '৯': 61, 'ঝিনুক': 62, 'কমলালেবু': 63, 'বাক্স': 64, 'কতগুলো': 65, 'মার্বেল': 66, '১': 67, 'বিস্কুট': 68, 'ডিম': 69, 'তাকে': 70, 'করেছেন': 71, 'কিছু': 72, 'হলে': 73, 'বেশি': 74, '৪০': 75, 'দিয়ে': 76, 'ভাগ': 77, '১৫': 78, 'ও': 79, 'লেবু': 80, 'বেগে': 81, 'আজ': 82, 'টুকরো': 83, 'কলা': 84, 'তাস': 85, 'তাদের': 86, 'চেয়ে': 87, 'থাকে': 88, 'ম

In [11]:
#word_index

In [12]:
# Padding the sequence

from tensorflow.keras.preprocessing.sequence import pad_sequences
max_length = 55
lines_pad = pad_sequences(sequence, maxlen = max_length, padding ='post')
lines_pad[0]

array([1283,   72,   66,    5,    1,   16, 1741,   66,  126,    1,   17,
         12,   58,   60, 1882,   66,    5,    1,   16,   20,   76,  106,
         96,    3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [13]:
#categorical to numerical
df["Class"] = df["Class"].map({' -':0, '-':0, ' +':1, '+':1, '*':2, ' *':2, '/':3})

<ipython-input-13-363898555310>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Class"] = df["Class"].map({' -':0, '-':0, ' +':1, '+':1, '*':2, ' *':2, '/':3})


In [14]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Problem, Equation, Sollution, Class]
Index: []

In [15]:
# Shuffle our dataset
import numpy as np
category = df["Class"].values

indices = np.arange(lines_pad.shape[0])
np.random.shuffle(indices)
lines_pad = lines_pad[indices]
category = category[indices]

In [16]:
category

array([1, 1, 1, ..., 1, 2, 0])

In [17]:
#Convert the classes into one hot vector
n_values = np.max(category) + 1
y = np.eye(n_values)[category]

In [18]:
y[0]

array([0., 1., 0., 0.])

In [19]:
lines_pad[0]

array([3867,  315,  705,   21, 1308,   21,  293,  774,   13,   41,  705,
         21, 1308,   21,  293,  150,   79,  170,  705,   21, 1308,   21,
        293, 3293,  217,  348,   13,   16,    8,    4,  293,  217,  348,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [20]:
# Split the dataset
#manually splitting
split_data = 0.2
num_split_samples = int(split_data*lines_pad.shape[0])

x = lines_pad[:-num_split_samples]
y = y[ :-num_split_samples]
x_test = lines_pad[-num_split_samples:]
y_test = y[-num_split_samples:]

In [21]:
num_split_samples #test data

1731

In [22]:
y

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

## Best performing model - LSTM

In [23]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [24]:
Lstm_model= Sequential()

Lstm_model.add(LSTM(units = 100, return_sequences = True, input_shape = (x.shape[1], 1)))
Lstm_model.add(Dropout(0.2))

'''Lstm_model.add(LSTM(units = 100, return_sequences = True))
Lstm_model.add(Dropout(0.2))

Lstm_model.add(LSTM(units = 100, return_sequences = True))
Lstm_model.add(Dropout(0.2))'''

Lstm_model.add(LSTM(units = 100))
Lstm_model.add(Dropout(0.2))

Lstm_model.add(Dense(units = 4, activation='softmax'))

#Lstm_model.compile(optimizer = 'adam', loss = 'mean_squared_error')
Lstm_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
Lstm_model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 55, 100)             │          40,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 55, 100)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 100)                 │          80,400 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 100)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 4)                   │             404 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 121,604 (475.02 KB)

 Trainable params: 121,604 (475.02 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
print('Train....')

history=Lstm_model.fit(x, y, batch_size=32, epochs=100, validation_data=(x_test, y_test))

Train....
Epoch 1/100
217/217 ━━━━━━━━━━━━━━━━━━━━ 28s 115ms/step - accuracy: 0.3770 - loss: 1.2848 - val_accuracy: 0.2900 - val_loss: 1.4098
Epoch 2/100
217/217 ━━━━━━━━━━━━━━━━━━━━ 37s 97ms/step - accuracy: 0.4374 - loss: 1.2060 - val_accuracy: 0.3276 - val_loss: 1.4741
Epoch 3/100
217/217 ━━━━━━━━━━━━━━━━━━━━ 47s 125ms/step - accuracy: 0.4668 - loss: 1.1262 - val_accuracy: 0.3131 - val_loss: 1.5757
Epoch 4/100
217/217 ━━━━━━━━━━━━━━━━━━━━ 33s 88ms/step - accuracy: 0.4858 - loss: 1.0882 - val_accuracy: 0.3247 - val_loss: 1.5782
Epoch 5/100
217/217 ━━━━━━━━━━━━━━━━━━━━ 21s 91ms/step - accuracy: 0.5137 - loss: 1.0449 - val_accuracy: 0.2929 - val_loss: 1.6109
Epoch 6/100
217/217 ━━━━━━━━━━━━━━━━━━━━ 21s 92ms/step - accuracy: 0.5238 - loss: 1.0230 - val_accuracy: 0.3027 - val_loss: 1.6730
Epoch 7/100
217/217 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.5242 - loss: 0.9891 - val_accuracy: 0.2842 - val_loss: 1.8663
Epoch 8/100
217/217 ━━━━━━━━━━━━━━━━━━━━ 22s 95ms/step - accuracy: 0.55

In [26]:
# Save the entire model (architecture, weights, and optimizer)
path = r"/content/drive/MyDrive/LSTM_model_BMWP.h5"
Lstm_model.save(path)


In [37]:
# Predict the operator
def generate_text_seq(model, tokenizer, seed_text, max_length):
  bnltk_token = tokens = t.bn_word_tokenizer(seed_text)
  encoded= tokenizer.texts_to_sequences([seed_text])[0]
  encoded= pad_sequences([encoded], maxlen = max_length, padding ='post')
  y_predict= np.argmax(model.predict(encoded), axis=-1)

  return y_predict


In [90]:
#Taking input problem
input_word = 'প্রথম সারিতে ৫৫ টি ইট ,২য় সারিতে ৮৮ ,তৃতীয় সারিতে ৩৩ টি ইট আছে। এখানে মোট কটি ইট সাজানো আছে লেখ।'
max_length = 55

#Function call
predicted_operator = generate_text_seq(Lstm_model, tokenizer, input_word, max_length)
print('Predicted_operator:  ', predicted_operator[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Predicted_operator:   1


In [31]:
{' -':0, '-':0, ' +':1, '+':1, '*':2, ' *':2, '/':3}

{' -': 0, '-': 0, ' +': 1, '+': 1, '*': 2, ' *': 2, '/': 3}